version: '3.8'

services:
  votingbot:
    image: toastyman231/votingbot:latest
    container_name: votingbot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped